name: Build and Publish Rust Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: cargo-strip

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary with cargo-strip
        run: cargo strip --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: icemodoro-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/icemodoro${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
