name: Lint and Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Rust Linting and Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          override: true

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy with pedantic lints
        run: cargo clippy -- -W clippy::pedantic

      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@v1
        with:
          denyWarnings: true
