name: Lint and Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Rust Linting and Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo bin
        uses: actions/cache@v4
        id: cache-cargo-bin
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: cargo-bin-${{ runner.os }}-

      - name: Install cargo-audit if needed
        if: steps.cache-cargo-bin.outputs.cache-hit != 'true'
        run: cargo install cargo-audit --locked

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy with pedantic lints
        run: cargo clippy -- -W clippy::pedantic

      - name: Run cargo audit
        run: cargo audit
