name: Lint and Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Rust Linting and Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-registry-${{ runner.os }}-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-build-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-build-${{ runner.os }}-

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          override: true

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy with pedantic lints
        run: cargo clippy -- -W clippy::pedantic

      - name: Run cargo audit via audit-check action
        uses: rustsec/audit-check@v2.0.0
