name: Lint and Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Rust Linting and Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          override: true

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy with pedantic lints
        run: cargo clippy -- -W clippy::pedantic

      - name: Run cargo audit via audit-check action
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
